# Generated by Django 3.2.5 on 2021-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('COLD', 'COLD'), ('HOT', 'HOT'), ('SMOOTHIE', 'SMOOTHIE'), ('PROMO', 'PROMO'), ('LUNCH', 'LUNCH'), ('BREAKFAST', 'BREAKFAST'), ('SPECIAL', 'SPECIAL'), ('DONUT', 'DONUT')], max_length=200)),
            ],
        ),
    ]
