# Generated by Django 3.2.5 on 2021-08-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_donut_retail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beverages',
        ),
    ]
