# Generated by Django 3.2.5 on 2021-08-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_delete_beverages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverages_updated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price_s', models.IntegerField()),
                ('price_m', models.IntegerField()),
                ('price_l', models.IntegerField()),
                ('desc', models.TextField()),
                ('type', models.CharField(choices=[('COLD', 'COLD'), ('HOT', 'HOT'), ('SMOOTHIE', 'SMOOTHIE'), ('PROMO', 'PROMO'), ('LUNCH', 'LUNCH'), ('BREAKFAST', 'BREAKFAST'), ('SPECIAL', 'SPECIAL'), ('DONUT', 'DONUT')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_sandwich', models.CharField(choices=[('WHITE', 'WHITE'), ('WHOLE WHEAT', 'WHOLE WHEAT'), ('MULTIGRAIN', 'MULTIGRAIN')], max_length=255)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('donation_price', models.FloatField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
