# Generated by Django 3.2.5 on 2021-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='newfld',
            field=models.CharField(default='asjik', max_length=100),
            preserve_default=False,
        ),
    ]
